In [1]:
#!/usr/bin/env conda run -n newenv1 python
import sys
import os
print(sys.executable)
print(sys.version)
print(os.getcwd())
print(sys.prefix)

C:\ProgramData\Anaconda3_1\envs\newenv1\python.exe
3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)]
C:\Users\fpe\JUPYTER\datirocce
C:\ProgramData\Anaconda3_1\envs\newenv1

In [15]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import matplotlib

In [3]:
import dash
import dash_html_components as html
import dash_core_components as dcc

In [27]:
df1 = pd.read_hdf('dati_rocce.h5', key='df1')
df1

,name,dry_weight,water_cont,UCS,elastic_mod,poisson,type,rock_type,pred_class
0,BS-1,2805,0.83,149.20,52.500000,0.2600,1,NaN,4
1,BS-2,2732,0.84,125.60,54.600000,0.2600,1,NaN,4
2,BS-3,2758,0.91,83.40,58.100000,0.1400,1,NaN,0
3,BS - 4,2240,4.78,24.40,15.900000,0.1800,1,NaN,2
4,BS - 5,2578,5.09,22.60,16.600000,0.3900,1,NaN,2
...,...,...,...,...,...,...,...,...,...
91,PYR-4,1674,5.29,9.20,5.600000,0.1900,3,NaN,1
92,PYR-5,1586,4.81,9.30,6.700000,0.4100,3,NaN,1
93,PYR-6,2145,4.22,8.60,4.400000,0.4000,3,NaN,1
94,PYR - 7,2000,12.31,3.54,6.983597,0.1822,3,NaN,1
95,PYR - 9,1869,6.30,7.00,8.000000,0.1500,3,NaN,1

In [5]:
df1.to_csv('df1.csv')
df1 = pd.read_csv('df1.csv',index_col=0)

In [26]:
df1.round(2)

,name,dry_weight,water_cont,UCS,elastic_mod,poisson,type,rock_type,pred_class
0,BS-1,2805,0.83,149.20,52.50,0.26,1,NaN,4
1,BS-2,2732,0.84,125.60,54.60,0.26,1,NaN,4
2,BS-3,2758,0.91,83.40,58.10,0.14,1,NaN,0
3,BS - 4,2240,4.78,24.40,15.90,0.18,1,NaN,2
4,BS - 5,2578,5.09,22.60,16.60,0.39,1,NaN,2
...,...,...,...,...,...,...,...,...,...
91,PYR-4,1674,5.29,9.20,5.60,0.19,3,NaN,1
92,PYR-5,1586,4.81,9.30,6.70,0.41,3,NaN,1
93,PYR-6,2145,4.22,8.60,4.40,0.40,3,NaN,1
94,PYR - 7,2000,12.31,3.54,6.98,0.18,3,NaN,1
95,PYR - 9,1869,6.30,7.00,8.00,0.15,3,NaN,1

In [ ]:
#######################################
############### LOAD DF  ##############



df1 = pd.read_csv(r"df1.csv",index_col=0)
df5 = pd.read_csv(r"df5.csv",index_col=0)

#######################################
############### PLOTLY   ##############





labels={'elastic_mod':'E Young [GPa]','UCS':'UCS  [MPa]', 'dry_weight':'Dry weight [kg/mÂ³]'}
symbol_sequence=[0,200,1,201,28]



width = 1200
height = 600






size=(df1.dry_weight)**4
fig = px.scatter(df1, x="UCS", y="elastic_mod", color="pred_class",
                 size=size, labels=labels, hover_data=['dry_weight','name','poisson','water_cont','rock_type','type','pred_class'],opacity=0.5,log_x=True,log_y=True)

fig.update_layout({'legend_orientation':'h'})

fig.update_layout(title='Elastic modulus - UCS - Classification',
    autosize=False,
    width=width,
    height=height)






size1=df1.UCS-df1.UCS.max()/df1.UCS.max()
fig1 = px.scatter(df1, x="dry_weight", y="elastic_mod", color="pred_class",labels=labels,
                 size=size1, hover_data=['dry_weight','name','poisson','water_cont','rock_type','type','pred_class'],opacity=0.5)

fig1.update_layout({'legend_orientation':'h'})

fig1.update_layout(title='Elastic modulus - dry weight - Classification',
    autosize=True,
    width=width,
    height=height)













#######################################################
#######################################################
#######################################################


x = "dry_weight"
y = "elastic_mod"

size4=df5.UCS-df5.UCS.max()/df5.UCS.max()
fig4 = px.scatter(df5, x=x, y=y, color="pred_class",symbol="rock_type",symbol_sequence=symbol_sequence,labels=labels,
                 size=size4, hover_data=['dry_weight','name','poisson','water_cont','rock_type','type','pred_class'],opacity=0.6) #text="name"

fig4.update_layout(title='Elastic modulus - dry weight - Classification', autosize=False, width=width, height=height)

fig4.update_layout({'legend_orientation':'h'})




##############################################Ã 


# size5=(df5.dry_weight)**4
# fig5 = px.scatter(df5, x="UCS", y="elastic_mod", color="pred_class",symbol="rock_type",symbol_sequence=symbol_sequence,
#                  size=size5, hover_name="rock_type",hover_data=['dry_weight','name','poisson','water_cont','rock_type',
#                 'type','pred_class'],opacity=0.6, log_y=True, log_x=True,labels=labels)


# fig5.update_layout({'legend_orientation':'h'})

# x1 = np.linspace(3,30,2000)
# y1 = x1*1.8
# y2 = x1*1
# y3 = x1*0.5
# y4 = x1*0.2

# fig5.add_scatter(x=x1, y=y1, mode="lines", line = dict(color='royalblue', width=1, dash='dash'), name='Mod_R=1800')
# fig5.add_scatter(x=x1, y=y2, mode="lines", line = dict(color='red', width=1, dash='dash'), name='Mod_R=1000')
# fig5.add_scatter(x=x1, y=y3, mode="lines", line = dict(color='green', width=1, dash='dash'), name='Mod_R=500')
# fig5.add_scatter(x=x1, y=y4, mode="lines", line = dict(color='grey', width=1, dash='dash'), name='Mod_R=200')

# fig5.add_trace(go.Scatter(hovertemplate =
#                     '<i>UCS</i>: $%{df5.UCS:.2f}'+
#                     '<br><b>E modulus</b>: %{elastic_mod}<br>'+
#                     '<b>%{text}</b>'))


# fig5.update_layout(title='Elastic modulus - UCS - Classification', 
#                    autosize=False, width=width, height=height,
#                     showlegend = False


#############   PROVA CON GO SCATTER  IMPORTA GO  ###################################



# Add trace with large markers

size5=(df5.dry_weight)**4

    
fig5 = go.Figure(
    go.Scatter(
        mode='markers',
        x=df5.UCS,
        y=df5.elastic_mod,
        marker=dict(
            color='rgba(135, 206, 250, 0.5)',
            size=size5,
            line=dict(
                color='Black',
                width=1
            ),
        ),
        hovertemplate =
            '<i>UCS</i>: $%{df5.UCS:.2f}'+
            '<br><b>E modulus</b>: %{df5.elastic_mod}<br>',
        showlegend=False
    ))






#####################################
############### DASH   ##############


app.layout = html.Div([

    html.Div([
        html.Img(src="/assets/geodata_logop.png")
    ]),

    html.Div([
        html.H2("PH rock Characterization Graphs based on rock sample laboratory tests"),
    ], className="banner"),

    html.Div([
        html.Img(src="/assets/panel__.jpg")
    ]),

    html.Div([
        html.H2("KMeans classification all samples"),
    ]),

    html.Div([
        html.Div([dcc.Graph(figure=fig)]),
        html.Div([dcc.Graph(figure=fig1)])
    ], className="row"),

    html.Div([
        html.H2("KMeans classification weak Basalt samples"),
    ]),

    html.Div([
        html.Div([dcc.Graph(figure=fig4)]),
        html.Div([dcc.Graph(figure=fig5)])
    ], className="row"),

    html.Div([
        html.H3("                      Fabrizio Peruzzo Â© Geodata S.p.a 2020   "),
    ])

])

app.css.append_css({
    "external_url":"https://codepen.io/chriddyp/pen/bWLwgP.css"
})



# Tolto 2 grafici su una linea perchÃ© non si scalavano
# html.Div([
#     html.Div([dcc.Graph(figure=fig4)], style={'width': '48%', 'display': 'inline-block'}),
#     html.Div([dcc.Graph(figure=fig5)], style={'width': '48%', 'display': 'inline-block'})
# ], className="row")





###########################################################################################################
# this change
app.run_server(debug=True, use_reloader=False)  # Turn off reloader if inside Jupyter

Running on http://127.0.0.1:8050/
Debugger PIN: 708-838-388
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on

C:\ProgramData\Anaconda3_1\envs\newenv1\lib\site-packages\dash\resources.py:68: UserWarning:

You have set your config to `serve_locally=True` but A local version of https://codepen.io/chriddyp/pen/bWLwgP.css is not available.
If you added this file with `app.scripts.append_script` or `app.css.append_css`, use `external_scripts` or `external_stylesheets` instead.
See https://dash.plot.com/external-resources