In [1]:
import numpy as np
import tabula
import pandas as pd
import PyPDF2
import re
import os
import warnings
warnings.filterwarnings('ignore')
warnings.filterwarnings(action='once')

In [2]:
path = os.getcwd()+'\\Reports'

files = []
filespath = []
# r=root, d=directories, f = files
for r, d, f in os.walk(path):
    for file in f:
        if '.pdf' in file:
            files.append(file)
            filespath.append(os.path.join(r, file))

In [3]:
filespath

['C:\\Users\\fpe\\JUPYTER\\datirocce\\Reports\\Rock-Test_ocr.pdf']

In [5]:
pdf_file = filespath[0]

df = tabula.read_pdf(pdf_file, pages='all')

In [8]:
df[1]

for

,Unnamed: 0,I,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,D ep t h ( rn ),NaN,NaN,w,I,Yd,NaN,I,crucs,I,Es,I,NaN,v,NaN,lscso>,T
1,#,3) From To,Layer,NaN,(%),NaN,(kN/m,NaN,NaN,(MPa),NaN,(GPa),NaN,NaN,-,-,(MPa),(MPa)
2,1,7 . 5 7 . 8,NaN,NaN,3,NaN,2 4 . 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4 . 1 1,6 . 6 1
3,NaN,NaN,"Basalt, fresh",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,9 . 0 9 . 2,NaN,NaN,1,NaN,2 8 . 0,NaN,NaN,1 1 8 . 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,3,1 3 . 9 1 4 . 0,"Pyroclastics,",NaN,4,NaN,2 2 . 8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 . 3 9,2 . 4 9
6,4,1 6 . 5 1 6 . 8,moderately,NaN,8,NaN,1 8 . 8,NaN,NaN,2 . 5 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0 . 9 7
7,5,1 9 . 7 2 0 . 0,weathered,NaN,6,NaN,2 0 . 3,NaN,NaN,1 6 . 5,NaN,4 . 3,NaN,0,. 1 4,NaN,NaN,1 . 5 7
8,"Py roe lastics, 6",2 3 . 7 2 4 . 0,NaN,NaN,6,NaN,1 9 . 8,NaN,NaN,1 4 . 5 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 . 8 5
9,NaN,NaN,fresh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,7,2 5 . 1 2 5 . 4,NaN,NaN,1,NaN,2 7 . 7,NaN,NaN,2 6 . 8 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9 . 5 3
11,8,2 9 . 8 3 0 . 0,NaN,NaN,5,NaN,1 8 . 8,NaN,NaN,1 3 . 0 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 . 5 3
12,9,3 4 . 5 3 4 . 9,NaN,NaN,3,NaN,2 4 . 0,NaN,NaN,4 7 . 2 8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4 . 3 4
13,1 0,3 7 . 7 3 7 . 9,NaN,NaN,1,NaN,2 6 . 6,NaN,NaN,7 8 . 4 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7 . 6
14,1 1,3 8 . 4 3 8 . 6,NaN,NaN,4,NaN,2 1 . 2,NaN,NaN,1 6 . 6,NaN,1 0 . 3,NaN,0 . 2 7,NaN,NaN,NaN,1 . 0 2
15,1 2,4 3 . 7 4 3 . 9,NaN,NaN,1,NaN,2 7 . 1,NaN,NaN,9 3 . 7 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1 3,4 6 . 5 4 7 . 0,NaN,NaN,2,NaN,2 6 . 3,NaN,NaN,9 1 . 2 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7 . 4 7
17,1 4,5 0 . 2 5 0 . 6,NaN,NaN,1,NaN,2 5 . 8,NaN,NaN,3 6 . 1 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 2 . 4 8
18,NaN,NaN,"Basalt, fresh",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1 5,5 2 . 3 5 2 . 9,NaN,NaN,1,NaN,2 6 . 8,NaN,NaN,7 0 . 2 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9 . 1 9
20,1 6,5 6 . 4 5 6 . 8,NaN,NaN,1,NaN,2 5 . 9,NaN,NaN,1 8 . 9,NaN,4 9 . 5,NaN,0,. 1 8,NaN,NaN,8 . 2 4
21,1 7,5 8 . 6 5 8 . 9,NaN,NaN,4,NaN,2 2 . 7,NaN,NaN,2 . 6 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 . 3 5
22,1 8,6 0 . 0 6 0 . 2,NaN,NaN,1,NaN,2 6 . 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8 . 3 7
23,1 9,6 4 . 2 6 4 . 4,NaN,NaN,1,NaN,2 7 . 2,NaN,NaN,2 5 . 2 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,20,6 8 . 9 6 9 . 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5 . 3 2,NaN
25,2 1,7 1 . 7 7 2 . 1,NaN,NaN,1,NaN,2 7 . 4,NaN,NaN,1 6 8 . 2 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 0 . 8 9
26,22,7 5 . 5 7 5 . 7,NaN,NaN,0,NaN,2 7 . 8,NaN,NaN,1 0 9 . 4 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 1 . 9 2
27,23,7 8 . 9 7 9 . 2,NaN,NaN,3,NaN,1 7 . 9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0 . 3,0 . 7 3
28,24,8 1 . 6 8 2 . 3,"Py roe lastics,",NaN,4,NaN,1 5 . 3,NaN,NaN,1 0 . 3,NaN,4 . 9,NaN,0 . 2 6,NaN,NaN,NaN,1 . 8 4
29,NaN,NaN,moderately,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,25,8 4 . 7 8 5 . 0,NaN,NaN,3,NaN,2 1 . 4,NaN,NaN,8 . 5 9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 . 1 6
31,NaN,NaN,weathered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,26,8 8 . 2 8 8 . 4,NaN,NaN,6,NaN,1 5 . 6,NaN,NaN,6 . 9 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,27,9 1 . 7 9 2 . 0,NaN,NaN,2,NaN,2 5 . 9,NaN,NaN,7 3 . 5,NaN,4 3 . 3,NaN,0 . 2 4,NaN,NaN,NaN,8 . 8 4
34,28,9 4 . 9 9 5 . 1,"Basalt, fresh",NaN,1,NaN,2 7 . 0,NaN,NaN,4 2 . 6 8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,29,9 8 . 1 9 8 . 6,NaN,NaN,1,NaN,2 7 . 2,NaN,NaN,1 1 5 . 1 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9 . 3
36,NaN,NaN,"Py roe lastics,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,30,1 0 1 . 8 1 0 2 . 3,moderately,NaN,3,NaN,2 0 . 4,NaN,NaN,1 7 . 6,NaN,4 . 7,NaN,0,. 1,NaN,NaN,2 . 0 1
38,NaN,NaN,weathered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,3 1,1 0 5 . 1 1 0 5 . 5,"Basalt, fresh",NaN,1,NaN,2 7 . 2,NaN,NaN,3 0 . 2 6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 5 . 8 1
40,32,1 0 7 . 8 1 0 8 . 3,"Py roe lastics,",NaN,4,NaN,2 1 . 5,NaN,NaN,1 4 . 4 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2 . 0 2
41,33,1 1 1 . 6 1 1 2 . 1,moderately,NaN,1,NaN,2 7 . 8,NaN,NaN,1 2 9 . 4 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 5 . 5 5